# Generated by Django 5.2.17 on 2026-09-13 08:52

import django.db.models.deletion
import django.utils.timezone
import monitor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DingTalkChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="群名称")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("US", "美站"),
                            ("DE", "德站"),
                            ("HK", "港站"),
                            ("SG", "新加坡站"),
                            ("UK", "英站"),
                            ("ALL", "综合群"),
                        ],
                        max_length=8,
                        verbose_name="站点",
                    ),
                ),
                (
                    "webhook_url",
                    monitor.fields.EncryptedTextField(verbose_name="Webhook 地址"),
                ),
                (
                    "secret",
                    monitor.fields.EncryptedTextField(
                        blank=True, verbose_name="加签密钥"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "钉钉群",
                "verbose_name_plural": "钉钉群",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000, unique=True, verbose_name="商品 URL"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="商品名称"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="商品图片"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用监控")),
                (
                    "interval_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="检查间隔（分钟）"
                    ),
                ),
                (
                    "notify_site_group",
                    models.BooleanField(default=True, verbose_name="通知站点群"),
                ),
                (
                    "notify_all_group",
                    models.BooleanField(default=True, verbose_name="通知综合群"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="运营备注")),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近检查"
                    ),
                ),
                (
                    "next_check_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="下次检查",
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最近错误")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "监控商品",
                "verbose_name_plural": "监控商品",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="代码")),
                ("name", models.CharField(max_length=100, verbose_name="商城名称")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("US", "美站"),
                            ("DE", "德站"),
                            ("HK", "港站"),
                            ("SG", "新加坡站"),
                            ("UK", "英站"),
                            ("ALL", "综合群"),
                        ],
                        max_length=8,
                        verbose_name="所属站点",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="主域名"
                    ),
                ),
                (
                    "adapter",
                    models.CharField(
                        default="generic", max_length=64, verbose_name="解析器"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "default_interval_minutes",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="默认检查间隔（分钟）"
                    ),
                ),
                (
                    "parser_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="自定义解析配置"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近成功"
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(default=0, verbose_name="连续失败"),
                ),
            ],
            options={
                "verbose_name": "商城",
                "verbose_name_plural": "商城",
            },
        ),
        migrations.CreateModel(
            name="CrawlFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(max_length=100, verbose_name="错误类型"),
                ),
                ("message", models.TextField(verbose_name="错误信息")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发生时间"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="monitor.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "抓取异常",
                "verbose_name_plural": "抓取异常",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="monitor.site",
                verbose_name="商城",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default="default", max_length=200, verbose_name="规格标识"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="默认规格", max_length=200, verbose_name="规格名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, max_length=8, verbose_name="币种"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "无法判断"),
                            ("out_of_stock", "缺货"),
                            ("in_stock", "有货"),
                            ("discontinued", "下架"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="确认库存",
                    ),
                ),
                (
                    "candidate_status",
                    models.CharField(
                        choices=[
                            ("unknown", "无法判断"),
                            ("out_of_stock", "缺货"),
                            ("in_stock", "有货"),
                            ("discontinued", "下架"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="待确认库存",
                    ),
                ),
                (
                    "candidate_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="连续确认次数"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近出现"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="monitor.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品规格",
                "verbose_name_plural": "商品规格",
            },
        ),
        migrations.CreateModel(
            name="StockSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observed_status",
                    models.CharField(
                        choices=[
                            ("unknown", "无法判断"),
                            ("out_of_stock", "缺货"),
                            ("in_stock", "有货"),
                            ("discontinued", "下架"),
                        ],
                        max_length=32,
                        verbose_name="检测库存",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="检测时间"
                    ),
                ),
                (
                    "raw_hint",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="判断依据"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="monitor.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="monitor.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存快照",
                "verbose_name_plural": "库存快照",
            },
        ),
        migrations.CreateModel(
            name="StockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("unknown", "无法判断"),
                            ("out_of_stock", "缺货"),
                            ("in_stock", "有货"),
                            ("discontinued", "下架"),
                        ],
                        max_length=32,
                        verbose_name="原库存",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("unknown", "无法判断"),
                            ("out_of_stock", "缺货"),
                            ("in_stock", "有货"),
                            ("discontinued", "下架"),
                        ],
                        max_length=32,
                        verbose_name="新库存",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="补货价格",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="发生时间"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="monitor.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存事件",
                "verbose_name_plural": "库存事件",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="成功")),
                ("response_text", models.TextField(blank=True, verbose_name="响应")),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="monitor.dingtalkchannel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="monitor.stockevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知记录",
                "verbose_name_plural": "通知记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "channel"), name="unique_event_channel"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("product", "external_id"), name="unique_product_variant"
            ),
        ),
    ]
