# Generated by Django 5.2.17 on 2026-09-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockevent",
            options={"verbose_name": "补货记录", "verbose_name_plural": "补货记录"},
        ),
    ]
